version: '3.1'

volumes:
  owndb:
    driver: "${VOLUME_DRIVER}"
  owncloud_data:
    driver: "${VOLUME_DRIVER}"
  owncloud_apache2:
    driver: "${VOLUME_DRIVER}"
  proxy:
    driver: "${VOLUME_DRIVER}"
networks:
  docker-network:
    external: true
secrets:
  ${SSL_CERTIFICATE}:
    external: true
  ${SSL_CERTIFICATE_KEY}:
    external: true
  ${SSL_CERTIFICATE_CRT}:
    external: true
services:
  owndb:
    container_name: owndb
    image: mysql:${MYSQL_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
      - "3306:3306"
    networks:
      - docker-network
    volumes:
      - owndb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  owncloud:
    container_name: owncloud 
    image: xingjiudong/owncloud:${OWNCLOUD_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
       - "8443:443"
       - "81:80"
    depends_on:
       - "owndb"
    networks:
      - docker-network
    volumes:
      - owncloud_data:/var/www/html
      - owncloudapache2:/etc/apache2
    environment:
      - SSL_CERTIFICATE=${SSL_CERTIFICATE}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
      - SSL_CERTIFICATE_CRT=${SSL_CERTIFICATE_CRT}
    secrets:
      - ${SSL_CERTIFICATE}
      - ${SSL_CERTIFICATE_KEY}
      - ${SSL_CERTIFICATE_CRT}
  proxy:
    container_name: proxy
    image: xingjiudong/nginx:{NGINX_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    volumes:
      - proxy:/etc/nginx
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_A_IP=${SERVER_A_IP}
      - SERVER_B_IP=${SERVER_B_IP}
      - SERVER_C_IP=${SERVER_C_IP}
      - SSL_CERTIFICATE=${SSL_CERTIFICATE}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
    secrets:
      - ${SSL_CERTIFICATE}
      - ${SSL_CERTIFICATE_KEY}
